name: performance_interceptor
description: Intereceptors for Firebase peformance http Metric.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_performance: ^0.6.0

  http_interceptor: ^0.3.3
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
