name: performance_interceptor
description: Intereceptors for Firebase peformance http Metric.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_performance: any

  http_interceptor: any
  dio: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
